name: Application ON Push & PR DO Code check
on: [push, pull_request]

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
          
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "pubspec.yaml"

      - name: Setup flutter
        if: steps.check_files.outputs.files_exists == 'true'
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Check flutter sdk version
        if: steps.check_files.outputs.files_exists == 'true'
        run: flutter --version
      
      - name: Get dependencies
        if: steps.check_files.outputs.files_exists == 'true'
        run: flutter pub get
      
      - name: Setup Dart Code Metrics
        if: steps.check_files.outputs.files_exists == 'true'
        run: dart pub add --dev dart_code_metrics

      - name: Dart Code Metrics analyze
        if: steps.check_files.outputs.files_exists == 'true'
        run: dart run dart_code_metrics:metrics analyze ./ --fatal-warnings --fatal-performance --fatal-style
      
      - name: Dart Code Metrics check-unnecessary-nullable
        if: steps.check_files.outputs.files_exists == 'true'
        run: dart run dart_code_metrics:metrics check-unnecessary-nullable ./ --fatal-warnings --fatal-performance --fatal-style

      - name: Dart Code Metrics check-unused-files
        if: steps.check_files.outputs.files_exists == 'true'
        run: dart run dart_code_metrics:metrics check-unused-files ./ --fatal-warnings --fatal-performance --fatal-style

      - name: Dart Code Metrics check-unused-code
        if: steps.check_files.outputs.files_exists == 'true'
        run: dart run dart_code_metrics:metrics check-unused-code ./ --fatal-warnings --fatal-performance --fatal-style

      - name: Check formatting
        if: steps.check_files.outputs.files_exists == 'true'
        run: dart format . --set-exit-if-changed

      - name: Run tests
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          # run tests if `test` folder exists
          if [ -d test ]
          then
              flutter test -r expanded
          else
              echo "Tests not found."
          fi
